services:
  frontend:
    image: waldoethan/task-slayer-frontend:latest
    build:
      context: ./client
      target: ${NODE_ENV:-dev} # Use 'prod' on the Pi
    restart: always
    environment:
      - VITE_API_URL=/api
    networks:
      - app-network

  backend:
    image: waldoethan/task-slayer-backend:latest
    build: ./server
    restart: always
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/taskslayer
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
